# @formatter:off
{{- $typeValueEnvVars := list "string" "float64" "bool"}}
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: {{ .Values.workload }}
spec:
  {{- $default_image_repo := "" }}
  {{- if .Values.image.imageRepo }}
  {{- $default_image_repo = (print .Values.image.imageRepo "/") }}
  {{- end }}
  {{- if .Values.image.imageTag }}
  image: "{{ $default_image_repo }}{{ .Values.image.imageName | default .Values.projectName }}:{{ .Values.image.imageTag }}"
  {{- else }}
  image: "{{ $default_image_repo }}{{ .Values.image.imageName | default .Values.projectName }}"
  {{- end }}
  imagePullPolicy: {{ .Values.imagePullPolicy }}
  flinkVersion: {{ or .Values.image.flinkVersion "v1_15" }}
  {{- if .Values.flinkConfiguration }}
  flinkConfiguration:
  {{- range $key, $value := .Values.flinkConfiguration }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.serviceAccount }}
  serviceAccount: {{ .Values.serviceAccount | quote }}
  {{- end }}
  {{- with .Values.jobManager }}
  jobManager:
    {{- if and .memory .cpu }}
    resource:
      memory: {{ .memory }}
      cpu: {{ .cpu }}
    {{- end }}
    replicas: {{ or .replicaCount 1.0 }}
    podTemplate:
      spec:
        containers:
          - name: flink-main-container
      {{- end }}
            {{- if or .Values.jobManager.volumeMounts .Values.volumeMounts }}
            volumeMounts:
              {{- if .Values.jobManager.volumeMounts }}
              {{- toYaml .Values.jobManager.volumeMounts | nindent 12 }}
              {{- end }}
              {{- if .Values.volumeMounts }}
              {{- toYaml .Values.volumeMounts | nindent 12 }}
              {{- end }}
            {{- end }}
        {{- if or .Values.jobManager.volumes .Values.volumes }}
        volumes:
          {{- if .Values.jobManager.volumes }}
          {{- toYaml .Values.jobManager.volumes | nindent 8 }}
          {{- end }}
          {{- if .Values.volumes }}
          {{- toYaml .Values.volumes | nindent 8 }}
          {{- end }}
        {{- end }}
  {{- with .Values.taskManager }}
  taskManager:
    {{- if and .memory .cpu }}
    resource:
      memory: {{ .memory }}
      cpu: {{ .cpu }}
    {{- end }}
    replicas: {{ or .replicaCount 1.0 }}
    podTemplate:
      spec:
        {{- if .nodeSelector }}
        nodeSelector:
          {{- toYaml .nodeSelector | nindent 10 }}
        {{- end }}
        {{- if .tolerations }}
        tolerations:
          {{- toYaml .tolerations | nindent 10 }}
        {{- end }}
        {{- if or .nodeAffinity  .podAffinity }}
        affinity:
          {{- if .nodeAffinity }}
          nodeAffinity:
            {{- toYaml .nodeAffinity | nindent 12 }}
          {{- end }}
          {{- if .podAffinity }}
          podAffinity:
            {{- toYaml .podAffinity | nindent 12 }}
          {{- end }}
        {{- end }}
        containers:
          - name: flink-main-container
    {{- end }}
            {{- if or .Values.taskManager.volumeMounts .Values.volumeMounts }}
            volumeMounts:
              {{- if .Values.taskManager.volumeMounts }}
              {{- toYaml .Values.taskManager.volumeMounts | nindent 14 }}
              {{- end }}
              {{- if .Values.volumeMounts }}
              {{- toYaml .Values.volumeMounts | nindent 14 }}
              {{- end }}
            {{- end }}
        {{- if or .Values.taskManager.volumes .Values.volumes }}
        volumes:
          {{- if .Values.taskManager.volumes }}
          {{- toYaml .Values.taskManager.volumes | nindent 10 }}
          {{- end }}
          {{- if .Values.volumes }}
          {{- toYaml .Values.volumes | nindent 10 }}
          {{- end }}
        {{- end }}
  podTemplate:
    kind: Pod
    apiVersion: v1
    {{- with .Values.specAnnotations }}
    metadata:
      annotations:
      {{- if kindIs "string" . }}
      {{- toYaml . | b64dec | nindent 8 }}
      {{- else }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
    spec:
      imagePullSecrets:
        - name: {{ or .Values.imagePullSecrets "tiki-gcr" }}
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: flink-main-container
          {{- if .Values.envVars }}
          env:
            {{- range $key, $value := .Values.envVars }}
              {{- $tp := typeOf $value }}
              {{- if has $tp $typeValueEnvVars }}
              - name: {{ $key }}
                value: {{ $value | quote }}
                {{- else }}
              - name: {{ $key }}
                {{- toYaml $value | nindent 12 }}
                {{- end }}
              {{- end }}
          {{- end }}
          {{- if .Values.envFrom }}
          envFrom:
          {{- toYaml .Values.envFrom | nindent 12 }}
          {{- end }}
  {{- if .Values.ingress }}
  ingress:
    {{- toYaml .Values.ingress | nindent 4 }}
  {{- end }}
  {{- if .Values.mode }}
  mode: {{ .Values.mode }}
  {{- end }}
  {{- with .Values.job }}
  job:
    jarURI: {{ .jarURI }}
    parallelism: {{ or .parallelism 1 }}
    upgradeMode: {{ or .upgradeMode "savepoint" }}
    state: {{ or .state "running" }}
    {{- if .savepointTriggerNonce }}
    savepointTriggerNonce: {{ .savepointTriggerNonce }}
    {{- end }}
    {{- if .entryClass }}
    entryClass: {{ .entryClass }}
    {{- end }}
    allowNonRestoredState: {{ or .allowNonRestoredState true}}
    {{- if .args }}
    {{- if .initialSavepointPath }}
    initialSavepointPath: {{ .initialSavepointPath }}
    {{- end }}
    args:
      {{- range $value := .args }}
      - {{ $value | quote }}
      {{- end }}
    {{- end }}
  {{- end}}
